TYPO3:
  Jobqueue:
    Beanstalkd:
      testing:
        # Set to TRUE to enable functional testing against a beanstalkd server
        # enabled: TRUE
        client:
          hostname: 127.0.0.1
          port: 11300

  Flow:
     # disable reflection for non psr-0 compliant pheanstalk package
    object:
      excludeClasses:
       'pda.pheanstalk' : ['Pheanstalk.*']